# Generated by Django 5.2.6 on 2025-09-12 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('columnId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.columns')),
            ],
        ),
    ]
