# Generated by Django 5.1.5 on 2025-03-31 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cel', models.CharField(max_length=255)),
                ('ocup', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CadastroCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCurso', models.TextField()),
                ('tipo', models.CharField(choices=[('CAI', 'CAI'), ('CT', 'CT'), ('CS', 'CS'), ('FIC', 'FIC')], default='CT', max_length=3)),
                ('horaAula', models.FloatField()),
                ('siglaCurso', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.TextField()),
                ('sigla', models.CharField(max_length=10)),
                ('semestre', models.IntegerField()),
                ('cargahoraria', models.FloatField()),
                ('curso', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.cadastrocurso', verbose_name='curso que essa disciplina faz parte')),
            ],
        ),
    ]
