# Generated by Django 5.1.5 on 2025-03-25 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCurso', models.TextField()),
                ('horaAula', models.FloatField()),
                ('siglaCurso', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.TextField()),
                ('sigla', models.CharField(max_length=10)),
                ('semestre', models.IntegerField()),
                ('cargahoraria', models.FloatField()),
                ('curso', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.cadastrocurso', verbose_name='curso que essa diciplina faz parte')),
            ],
        ),
    ]
