# Generated by Django 5.1.5 on 2025-03-25 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cadastrocurso_cadastrodisciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrocurso',
            name='tipo',
            field=models.CharField(choices=[('CAI', 'CAI'), ('CT', 'CT'), ('CS', 'CS'), ('FIC', 'FIC')], default='CT', max_length=3),
        ),
        migrations.AlterField(
            model_name='cadastrodisciplina',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.cadastrocurso', verbose_name='curso que essa disciplina faz parte'),
        ),
    ]
